[tool.poetry]
name = "okx-analysis"
version = "0.1.0"
description = ""
authors = ["jack <jack@windfall.capital>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
